FROM python:3.10-slim

WORKDIR /app

# Instalar dependencias del sistema (incluye pg_isready)
RUN apt-get update && \
    apt-get install -y gcc libpq-dev curl postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Instalar herramientas para testing
RUN pip install pytest pytest-html pytest-flask requests

# Copiar el código y el script wait-for-db
COPY . .
COPY wait-for-db.sh .
RUN chmod +x wait-for-db.sh

ENV FLASK_APP=app.py
EXPOSE 5000
