version: "3.9"

services:
  db-test:
    image: postgres:13
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./scripts/test_data.sql:/docker-entrypoint-initdb.d/02_data.sql

  backend-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db-test
    env_file:
      - .env.test
    volumes:
      - .:/app
      - ./htmlcov:/app/htmlcov  # Volumen para el reporte HTML de coverage
      - ./report.html:/app/report.html  # Volumen para el reporte HTML de pytest
    entrypoint: ["sh", "wait-for-db.sh"]
    command: >
      sh -c "
        coverage run -m pytest tests/ &&
        coverage report -m &&
        coverage html &&
        pytest tests/ --html=report.html --self-contained-html
      "


